name: dm4bem-env

channels:
  - conda-forge

dependencies:
  - python=3.7.11
  - jupyter=1.0.0
  - jupyterlab=3.2.1
  - ipywidgets=7.6.5
  - matplotlib=3.4.3
  - numpy=1.20.3
  - scipy=1.7.1
  - pandas=1.3.4
